In [153]:
import pandas as pd
import numpy as np

from sklearn.model_selection import KFold ## for regression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold ## recommended for classification


from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Ridge, RidgeCV, Lasso, LassoCV
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
import lightgbm as lgb

In [154]:
df1 = pd.read_csv('UseData.csv')
df1

Day     S        T     K   Value     tau     rate
0      44834.0  2.65  0.24384  2.50  0.2092  0.0191  1.06000
1      44834.0  2.65  0.24384  2.55  0.1734  0.0191  1.03922
2      44834.0  2.65  0.24384  2.60  0.1400  0.0191  1.01923
3      44834.0  2.65  0.24384  2.65  0.1111  0.0191  1.00000
4      44834.0  2.65  0.24384  2.70  0.0882  0.0191  0.98148
...        ...   ...      ...   ...     ...     ...      ...
31729  44075.0  3.40  0.15616  3.40  0.1322  0.0250  1.00000
31730  44075.0  3.40  0.15616  3.50  0.0924  0.0250  0.97143
31731  44075.0  3.40  0.15616  3.60  0.0640  0.0250  0.94444
31732  44075.0  3.40  0.15616  3.70  0.0415  0.0250  0.91892
31733  44075.0  3.40  0.15616  3.80  0.0284  0.0250  0.89474

[31734 rows x 7 columns]

In [155]:
print(df1.isnull().sum()) #判断是否有无效值NaN
df1 = df1.dropna() # 删去无效值
df1.drop(df1[(df1.rate >= 1.15)|(df1.rate < 0.85)].index, inplace = True)
df1.shape

Day      0
S        0
T        0
K        0
Value    0
tau      0
rate     0
dtype: int64


(25947, 7)

In [156]:
X = df1.drop(['Day',"Value"],axis=1)
Y = df1.Value

## Regression

### Linear regression

In [163]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)
model_1 = LinearRegression()
model_1.fit(X_train,Y_train)

print(score)

0.8955371274857625


In [ ]:
kfolds_regresssion = KFold(n_splits = 5, random_state = 1, shuffle = True)

### Linear Regression with kfold

In [ ]:
tot = 0
niter = 0
for train_index, test_index in KFold(n_splits = 5, random_state = 1, shuffle = True).split(X,Y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    Y_train, Y_test = Y.iloc[train_index], Y.iloc[test_index]
    model1 = LinearRegression()
    model1.fit(X_train, Y_train)
    
    predictions = model1.predict(X_test)
    # print(predictions)
    # print(Y_test.values)
    score = model1.score(X_test, Y_test)
    tot += score
    niter += 1
    print(niter, score)
print(f'Mean Score of Linear Regression:', tot/niter*10000)

[ 0.23447729  0.16044321 -0.10036916 ... -0.01334972  0.0670222
  0.22717377]
[0.2092 0.14   0.0095 ... 0.0092 0.0849 0.2373]
1 0.8962385680794289
[0.09523595 0.06534297 0.03718962 ... 0.03911222 0.18783168 0.1429016 ]
[0.0882 0.0672 0.051  ... 0.0654 0.186  0.1322]
2 0.9013621699828137
[ 0.12723973 -0.01393958  0.03423418 ...  0.2938814   0.10273229
  0.06692784]
[0.1111 0.0287 0.0707 ... 0.333  0.0924 0.064 ]
3 0.8961483353341795
[ 0.1969022  -0.03674869 -0.05870654 ...  0.18628685  0.23764489
  0.00717663]
[0.1734 0.0205 0.0162 ... 0.1979 0.2533 0.0284]
4 0.8977962881116145
[0.11329564 0.08507667 0.01014053 ... 0.2723927  0.09139896 0.03493473]
[0.1231 0.1028 0.0584 ... 0.2826 0.1102 0.0415]
5 0.898879005429418
Mean Score of Linear Regression: 8980.84873387491
